server:
  port: 8091

spring:
  profiles:
    active: dev #默认为开发环境
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true #解决懒加载问题
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

 
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  
jwt:
  header: token #JWT存储的请求头
  secret: 507Secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

#七牛云
qiniu:
  accessKey: VTj1MSsrMPOOs-U9ZV1yWrAvEoW6pZPdIWaT7q6i
  secrectKey: BgdhhGycpIOXBYkY9Iu8LQrqqSf2SJ9Mk5CGEIsV
  bucket: crayfish
  host: https://upload-z2.qiniup.com
  cdnUrl: http://dssc.qn.cnyiliaosc.com
  zone: zone2



